# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180717_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 3, 27, 28, 824429, tzinfo=utc)),
        ),
    ]
